FROM rasa/rasa:3.6.21

USER root

WORKDIR /app

# Install additional dependencies (if needed)
RUN pip install --no-cache-dir numpy==1.23.5 spacy requests

# Switch back to default user
USER 1001

CMD ["run", "--enable-api", "--cors", "*", "--port", "5005"]